spring:
  application:
    name: game-love
  h2:
    console:
      enabled: true
      path: h2
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true


game-love:
  securityEnabled: ${SECURITY_ENABLED:true}
  jwtSecret: hopeyoulikemyprojectthanksforinterest
  pageSize: 50
  users:
    - username: admin
      password: admin
      roles:
        - ADMIN
        - USER
    - username: said
      password: said
      roles:
        - ADMIN
        - USER
  games:
    - name: Rrd2
    - name: CyberPunk2077
    - name: GTAV

